import React, { useState } from 'react';
import { X } from 'lucide-react';

interface Method {
  name: string;
  videoUrl: string;
}

interface SubPrompt {
  title: string;
  description: string;
  methods: Method[];
}

interface TeaserSectionProps {
  imageUrl: string;
  prompts: SubPrompt[];
}

export function TeaserSection({ imageUrl, prompts }: TeaserSectionProps) {
  const [isDialogOpen, setIsDialogOpen] = useState(false);
  const [activePrompt, setActivePrompt] = useState(0);

  const handleDialogClick = (e: React.MouseEvent) => {
    if (e.target === e.currentTarget) {
      setIsDialogOpen(false);
    }
  };

  return (
    <div className="w-full max-w-6xl mx-auto mb-16">
      {/* Main Teaser Image */}
      <div 
        className="relative aspect-w-16 aspect-h-9 rounded-lg overflow-hidden cursor-pointer hover:shadow-xl transition-shadow"
        onClick={() => setIsDialogOpen(true)}
      >
        <img
          src={imageUrl}
          alt="DecompDreamer Teaser"
          className="w-full h-full object-cover"
        />
      </div>
      <div className="p-4 sm:p-6">
        <p className="text-xs sm:text-lg text-gray-600 text-center">
          Illustration of high-quality, complex 3D scenes generated by DecompDreamer for prompts containing 6-11 objects. Existing methods struggle to generate all objects accurately and fail to maintain correct spatial relationships.
        </p>
      </div>

      {/* Dialog with Tabs */}
      {isDialogOpen && (
        <div 
          className="fixed inset-0 bg-black bg-opacity-50 z-50 flex items-center justify-center p-4"
          onClick={handleDialogClick}
        >
          <div className="bg-white rounded-xl w-full max-w-[95vw] max-h-[90vh] overflow-y-auto overflow-x-hidden shadow-2xl">
            {/* Prompt Tabs */}
            <div className="border-b border-gray-200 sticky top-0 bg-white z-10">
              <nav className="flex justify-center px-4 py-3 overflow-x-auto">
                <div className="inline-flex space-x-2">
                  {prompts.map((prompt, index) => (
                    <button
                      key={index}
                      className={`
                        px-6 py-2 text-sm font-medium rounded-full transition-all duration-200 transform hover:scale-110
                        ${activePrompt === index
                          ? 'bg-[#6366F1] text-white'
                          : 'text-gray-700 hover:bg-gray-50'
                        }
                      `}
                      onClick={() => setActivePrompt(index)}
                    >
                      {prompt.title}
                    </button>
                  ))}
                </div>
              </nav>
            </div>

            {/* Content */}
            <div className="p-6">
              <p className="text-2xl bg-gradient-to-r from-blue-600 to-violet-600 bg-clip-text text-transparent text-center font-semibold mb-8">
                {prompts[activePrompt].description}
              </p>
              
              <div className="flex flex-nowrap gap-4 overflow-x-auto pb-4">
                {prompts[activePrompt].methods.map((method, index) => (
                  <div key={index} className="flex-shrink-0 w-1/4 min-w-[300px] space-y-2">
                    <div className="aspect-w-16 aspect-h-9 bg-black rounded-lg overflow-hidden">
                      <video
                        src={method.videoUrl}
                        className="w-full h-full object-contain"
                        controls
                        autoPlay
                        loop
                        muted
                      />
                    </div>
                    <p className="text-center font-medium text-gray-700">
                      {method.name}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}